### ISSUE TITLE
API changes

### ISSUE THREAD

**Issue by joseivanlopez** [yast/yast-users#257]
Current API for users/groups was designed with the idea of creating immutable objects. Finally we have decided to leave that idea and to go with a more "classical" API.

This issue summarizes a proposal for adapting the current API, which:

* Allows to create users/groups without an associated config (useful in some scenarios, e.g., testing).
* Explicitly registers/unregisters users/groups into a config.
* Does not allow to edit the list of users/groups directly (register/unregister instead).
* Password is directly assigned to an user.
* An user/group can be cloned, which would generate a new unregistered user/group. 

Here is how the new API could look:

~~~
john = User.new("john")
john.gid = 100
john.primary_group #=> nil
john.groups #=> []
john.password = Password.new(plain: "S3Cr3T")

john.attached? #=> false
john.id #=> nil
john.config #=> nil

group1 = Group.new("john", gid: 100)
group2 = Group.new("users", users_name: ["john"])

john.groups #=> []

config = Config.new
config.attach(john, group1, group2)

john.attached? #=> true
john.id #=> 1
john.config #=> config
john.primary_group #=> group1
john.groups #=> [group1, group2]

config2 = config.clone #=> clone users and groups, keeping the same internal ids.
john2 = config2.users.find { |u| u.name == john.name }
john2.gecos = ["New name"]
john2.is?(john) #=> true (same #id)
john2 == john #=> false (different attributes, e.g. #gecos)
john2.password == john.password #=> true

john3 = john.clone #=> clones the user without copying its id and config
john3.id #=> nil
john3.config #=> nil
jonh3.attach_to(config2)
john3.is?(john) #=> false
john3.password == john.password #=> true

config2.users #=> [john2, john3]
config2.detach(john3) # or john3.detach
john3.id #=> nil
john3.config #=> nil
config2.users #=> [john2]
~~~

**Comment by jreidinger** [comment]
just few small notes to proposal:

- I prefer to have attach/detach instead of register/unregister. It sounds more familiar for me.
- is id writable?
- I am not sure if it is intention, but in example is used `user.group` but I still prefer `user.primary_group` to avoid confusion with groups method.
- not sure what will happen with if change user name with password, as passwords then cannot be same ( password contain user name )

**Comment by ancorgs** [comment]
`id` is only written when attaching (and set to nil when detached). It cannot be changed via a normal accesor at any other point in time.

The `user.group` in the example is not an intentional change. It would still be `user.primary_group`.

The idea is to remove the username from the `Password` class.

**Comment by jreidinger** [comment]
> `id` is only written when attaching (and set to nil when detaching). It cannot be changed via a normal accesor at any other point in time.
> 

ah, the part with reset to nil is missing in example. Now it makes more sense. So if I get it combination of config + id is unique and same ids can happen only when you clone whole config and is not reversible. So 
``` ruby
user2.is?(user1) # true
user2.detach
user2.attach(config2)
user2.is?(user1) # false
```
I think it can work if we document it properly and also attach some examples

**Comment by ancorgs** [comment]
> So if I get it combination of config + id is unique and same ids can happen only when you clone whole config and is not reversible.

Exactly.

**Comment by joseivanlopez** [comment]
https://github.com/yast/yast-users/pull/258
